version: '3'
services:
    course-service:
      build: ./course-service
      volumes:
        - ./course-service:/app
      ports:
        - 5001:8000
    website:
      # image: ngnix:alpine
      # volumes:
      #   - ./website:/app/share/ngnix/html
      build: ./website
      volumes:
        - ./website:/app
      ports:
        - 5002:80
      depends_on:
        - course-service